email_enabled: true
generate_transcript: true
filter_since_last_schedule: true
use_tts: true

ranking_model: gpt-5-2025-08-07
podcast_model: gpt-5-2025-08-07
tts_model: gpt-4o-mini-tts-2025-03-20
tts_voice: marin
tts_instructions_path: prompt/tts_instructions.txt
influence_filter_model: gpt-5-mini-2025-08-07
influence_prompt_path: prompt/prompt_influence_filter.j2
influence_score_threshold: 3
compress_to_64kbps: true
pricing_path: my_config/pricing.json
ir_limit: 50
nlp_limit: 50
others_limit: 50
keywords_path: my_config/keywords.yaml
top_n: 3
top_n_tts: 3
abst_word_cutoff: 200
transcript_word_cutoff: 1000
arxiv_timeout: 30
openai_timeout: 180
